#!/bin/sh

#PBS -N prepare_to_pair
#PBS -M patnatha@med.umich.edu
#PBS -m abe

#PBS -A leeschro_armis
#PBS -q armis
#PBS -l qos=armis

# Change the number of cores (ppn=1), amount of memory, and walltime:
#PBS -l nodes=1:ppn=8,pmem=12gb
#PBS -l walltime=5:00:00
#PBS -j oe
#PBS -V

####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#Load the R module
module load R 

#Submit the script 
Rscript step_01_prepare_to_pair.R $@

