rm -f ./Nate_LIMIT.o*
rm -f ./prepare_data.o*
rm -f ./prepare_selection.o*
rm -f ./tune_it_up.o*
rm -f ./intersect_tuneup.o*
rm -f ./post_process.o*
rm -f ./tune_intersect.o*
rm -f ./prepare_to_pair.o*
rm -f ./pair_values.o*
rm -f ./combine_pairs.o*
rm -f ./analyze_group.o*
rm -f ./count_files.o*
rm -f ./tune_exclude.o*
rm -f ./intersect_group.o*
rm -f ./sample_exclude.o*
